### ISSUE TITLE
Rename 'users' to 'principals'

### ISSUE THREAD

**Issue by evert** [curveball/a12n-server#103]
Given that a 'user' can be a 'user', 'app' or in the future also 'group', I think we should switch to a more generic name for this.

I would like to rename all 'users' apis to 'principals'. Almost everything else can remain the same.

When we do this, we should not remove the 'users' API. Instead, mark it as deprecated. We can do the removing of this API later, but this means that for a while we will have both a 'users' and a 'principals' API that are (mostly) identical.

**Comment by RShadowhand** [comment]
Rather than principals, I think the name "endpoint" is more apt, as it fits a user logging in from a browser, or through an app.

**Comment by evert** [comment]
So this endpoint doesn't really pertain to *where people logged in from*, but rather 'who they are'. So it's somewhat equivalent to a unix account, which can also be 'people', but sometimes also specific to applications/daemons.

So in this context, an app can have privileges too. The reason I landed on 'principal', is because it matches the naming convention from several other access control systems, the one I'm most familiar with is WebDAV, but there's others too. Endpoint is a bit too generic because in HTTP/REST services anything that has a url is really an endpoint.

**Comment by RShadowhand** [comment]
> So this endpoint doesn't really pertain to where people logged in from, but rather 'who they are'. 
That makes sense.
My idea of endpoints were user endpoints, a mobile app, a web login, etc. So then there would be endpoints _of_ a principal. (As opposed to endpoints of the API)

I'm currently checking out this repo, and I like what I see, figured I'd chime in. Keep up the good work! 😺

**Comment by juhangsin** [comment]
This has been completed by @evert 
https://github.com/curveball/a12n-server/pull/304
