### ISSUE TITLE
Successful notifications are stylized as errors

### ISSUE THREAD

**Issue by evert** [curveball/a12n-server#104]
When a user successfully requests to reset their password, they are met with a notification that looks more like an error. It's red and it has an alert symbol.

Lets fix this. This is partially a @ikbensiep thing for updating the style and a @juhangsin for updating the code.

I think the easiest way to handle this is that right now we have a `?msg=` query parameter. Perhaps we can just add an `?error=` query parameter and have each be styled appropriately.

**Comment by ikbensiep** [comment]
So I can update the template(s) like this: (and add appropriate styles)

```
{{# if msg}}
  <div class="msg">{{ msg }}</div>
  {{/if}}
  {{# if error}}
  <div class="msg error">{{ error }}</div>
  {{/if}}
```

but I woudn't know where to "create" errors, I do see the app creating a `msg` variable. 

How do I go from here?

**Comment by evert** [comment]
After the style changes, @juhangsin can update the controllers to redirect to ?error where appropriate =)

**Comment by juhangsin** [comment]
i'll work on this, and will let you know when i'm done @ikbensiep !
