### ISSUE TITLE
Make the login button the default button

### ISSUE THREAD

**Issue by evert** [curveball/a12n-server#319]
If a user goes to the login screen, and a browser password manager pre-fills the username and password, it should be possible for a user to just press the 'enter' button on their keyboard to submit the login form.

**Comment by juhangsin** [comment]
@evert: looks like the current behaviour works that way.
Flow: type user email & password --> press enter will submit for logging the user in.
Let me know if I misunderstood this! :)

![Screenshot from 2021-06-27 21-40-18](https://user-images.githubusercontent.com/28197089/123567496-494d5780-d790-11eb-81de-c9ba2f7f983a.png)

**Comment by evert** [comment]
I guess I ran into a situation where it doesn't work: if a browser password manager auto-fills the username/password (but I don't think it's true for external password managers like enpass)
