### ISSUE TITLE
Integrate WebAuthN

### ISSUE THREAD

**Issue by evert** [curveball/a12n-server#41]
WebAuthN is the new web api for integrating with systems like:

* Yubikeys (hardware keys)
* Windows Hello
* OS X Face ID

It would be great to have this as a 2FA option. But ideally this would be done after #26 to make it a bit easier to add this to the existing interface.

**Comment by mhum** [comment]
@evert, so I think this is done. However, I don't have a variety of devices that support WebAuthn to test with. The library that I used has a list of devices that it has been confirmed to work with:
https://simplewebauthn.dev/docs/advanced/supported-devices

**Comment by evert** [comment]
Awesome !! I'm exicted to test this all out, which is gonna be soon because 1 installation is due for an upgrade
