### ISSUE TITLE
When editing an OAuth2 client, the checkboxes for client grants are not checked

### ISSUE THREAD

**Issue by mhum** [curveball/a12n-server#420]
If I have an existing OAuth2 client with allowed grant types saved:
![image](https://user-images.githubusercontent.com/11312558/182882737-7b14bc37-7f3e-4499-ac01-266e508d049a.png)

Those checkboxes aren't checked when I edit the client:
![image](https://user-images.githubusercontent.com/11312558/182882849-1d01d2b6-84c7-4037-be25-550d7b3d870b.png)

I have to re-check them or else it saves the form and updates the client with **no** allowed grant types which is very confusing.

**Comment by syedfkabir** [comment]
This issue was closed due two changes:
https://github.com/badgateway/ketting/pull/451
https://github.com/curveball/browser/pull/146


I tested the issue @mhum was having after these PRs, and the issue is resolved.

**Comment by evert** [comment]
Was there a PR that updates these dependencies?

**Comment by syedfkabir** [comment]
> Was there a PR that updates these dependencies?

From what I understand, ketting got updated, so the browser needed a dependency update
is that correct?

**Comment by syedfkabir** [comment]
I was still testing my local browser changes against the media-api, I finally got it reverted and I see the issue is not resolved. One more step to go.

**Comment by evert** [comment]
Makes sense!

**Comment by evert** [comment]
This was fixed after merging #426
