### ISSUE TITLE
Upgrade to curveball v1 and fix PostgresQL compatibility issue

### ISSUE THREAD

**Issue by ICTServ** [curveball/a12n-server#488]
Please upgrade the dependencies. If you could add delete user/app UI and email verification feature it would make almost complete auth app since the it already has so many features. Thank you!

**Comment by evert** [comment]
I created some separate tickets to address these, they're all good ideas:

* #492 
* #491 
* #490 

However I'm not sure what compatibility issue with postgres you are referring to, lmk if you have more details. Thanks!
