### ISSUE TITLE
Authentication mode not supported MySQL 8.0.16

### ISSUE THREAD

**Issue by mihok** [curveball/a12n-server#51]
Running into an issue using the latest mysql version, something may have been deprecated or requires additional configuration beyond default configuration to support a12n-server out of the box.

So this may end up just be an update to documentation.

Tested on MySQL 5.7.26 and works fine.
Tested on MySQL 8.0.16 (via docker) and received the following error:

```{ Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at PromisePool.query (/home/mihok/development/src/github.com/savearthdigital/auth-api/node_modules/mysql2/promise.js:322:22)
    at Object.query (/home/mihok/development/src/github.com/savearthdigital/auth-api/node_modules/a12n-server/dist/database.js:20:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlState: '08004',
  sqlMessage:
   'Client does not support authentication protocol requested by server; consider upgrading MySQL client' }
```

**Comment by evert** [comment]
@juhangsin also ran into this. I wonder if there's a way we can support mysql 8

**Comment by mihok** [comment]
Probably fairly simple change to support it, I'll have a look later when I get some free time

**Comment by evert** [comment]
Maybe this is the solution: https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

**Comment by spidgorny** [comment]
I was able to fix it with
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'pass';
```

**Comment by evert** [comment]
I ran into this later, and basically realized that the root user on my laptop uses linux-style authentication to log in. Simply creating a new user + password fixed this for me. Probably a good idea to use a non-root user regardless.

Because this doesn't really feel like an a12n-server issue, I'm closing it.
