### ISSUE TITLE
Cli script should follow ESM

### ISSUE THREAD

**Issue by Zen-cronic** [curveball/a12n-server#555]
Running `npx @curveball/a12n-server` throws `ReferenceError: __dirname is not defined in ES module scope` due to [this](https://github.com/curveball/a12n-server/blob/f8ef1c7898959e8cd30d110805e2ebf898b021c7/bin/a12n-server#L12).

Fix: get the dirname this way https://github.com/curveball/a12n-server/blob/f8ef1c7898959e8cd30d110805e2ebf898b021c7/src/env.ts#L15

**Comment by evert** [comment]
Is it possible you're running an older cached copy of this?

**Comment by evert** [comment]
Oh oops, yes this is still an issue. Thanks for spotting !

**Comment by Zen-cronic** [comment]
i think so! But running `path/to/a12n-server/bin/a12n-server` (the node script file) also throws the same
