### ISSUE TITLE
Lost password functionality

### ISSUE THREAD

**Issue by evert** [curveball/a12n-server#85]
This feature is already underway, but will add a bit of a specification here (for the bits that are not already known).

Steps:

1. User clicks 'forgot password'
2. User fills in their email address
3. A unique unguessable one-time token gets generated
4. User receives an email with a link to: `https://auth-server.example/reset-password/token/[token]`
5. The session gets updated with a flag that means that the user is now allowed to change their password. For instance: `ctx.state.session.resetPassword = userId`
6. User gets redirected to a page where they may change their password. ``https://auth-server.example/reset-password/change-password`
7. This form sends a POST request to do the actual reset. Both 5 and 6 need to check if the resetPassword session information is set.
8. After the password is changed, remove the session tokens and redirect the user to the login page.

**Comment by juhangsin** [comment]
Completed
